version: "3"
services:
  simpleapp:
    image: mcallinan/simpleapp
    build:
      context: .
      args:
        - GIT_VERSION
        - GIT_COMMIT
    environment:
      VERSION: $GIT_VERSION
      LAST_COMMIT: $GIT_COMMIT
    ports:
      - 8000:8000
    command: npm start